<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search sample
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["sample/new", "Create sample"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "sample/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAge" class="col-sm-2 control-label">Age</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["age", "type" => "number", "class" => "form-control", "id" => "fieldAge"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSampleDate" class="col-sm-2 control-label">Sample Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sample_date", "type" => "date", "class" => "form-control", "id" => "fieldSampleDate"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
