<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["sample", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create sample
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "sample/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAge" class="col-sm-2 control-label">Age</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["age", "type" => "number", "class" => "form-control", "id" => "fieldAge"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSampleDate" class="col-sm-2 control-label">Sample Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sample_date", "type" => "date", "class" => "form-control", "id" => "fieldSampleDate"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
