<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["sample/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["sample/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Age</th>
            <th>Sample Of Date</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $sample): ?>
            <tr>
                <td><?php echo $sample->id ?></td>
            <td><?php echo $sample->name ?></td>
            <td><?php echo $sample->age ?></td>
            <td><?php echo $sample->sample_date ?></td>

                <td><?php echo $this->tag->linkTo(["sample/edit/" . $sample->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["sample/delete/" . $sample->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["sample/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["sample/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["sample/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["sample/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
